### ISSUE TITLE
Slim TYPO3 breaks TYPO3 scheduler

### ISSUE THREAD

**Issue by smichaelsen** [bnf/slim-typo3#3]
When calling the TYPO3 v8 scheduler with `./cli_dispatch.phpsh scheduler` the following error occurs:

````
Uncaught TYPO3 Exception Argument 1 passed to Bnf\SlimTypo3\Http\SlimRequestHandler::canHandleRequest() must be an instance of Psr\Http\Message\ServerRequestInterface, instance of Symfony\Component\Console\Input\ArgvInput given, called in /path/vendor/typo3/cms/typo3/sysext/core/Classes/Core/Bootstrap.php on line 289
thrown in file /path/web/typo3conf/ext/slim_typo3/Classes/Http/SlimRequestHandler.php
in line 178
````

I tracked it down to this spot in ext_localconf.php

````
if (TYPO3_REQUESTTYPE & (TYPO3_REQUESTTYPE_FE | TYPO3_REQUESTTYPE_BE | TYPO3_REQUESTTYPE_AJAX)) {
     // register slim request handler
}
````

When running the scheduler with the above command the `TYPO3_REQUESTTYPE` is `BE` & `CLI` so the request handler is registered when it shouldn't.

This would be the right condition:

````
if (!(TYPO3_REQUESTTYPE & (TYPO3_REQUESTTYPE_CLI | TYPO3_REQUESTTYPE_INSTALL))) {
````

**Comment by smichaelsen** [comment]
PR incoming

**Comment by bnf** [comment]
It's by design to match for `TYPO3_REQUESTTYPE_BE` to be able to register routes for `/typo3` as well. Therefore I would like to keep that. We'll need another condition to circumvent the issue you discovered.

**Comment by smichaelsen** [comment]
With the new condition BE is possible. The Handler will not be registered if the request contains CLI or INSTALL.
*Edit*: Sorry, I corrected an error in the first snippet that was misleading.

**Comment by bnf** [comment]
Ah, sorry, I misread your comment – it's all fine.
Although I like whitelists more and therefore thought about something like:
`if (TYPO3_REQUESTTYPE & (TYPO3_REQUESTTYPE_FE | TYPO3_REQUESTTYPE_BE | TYPO3_REQUESTTYPE_AJAX) && !(TYPO3_REQUESTTYPE & TYPO3_REQUESTTYPE_CLI))`, I'd still merge your blacklist variant as it's way shorter. Will merge your PR.
